import {useEffect,useMemo,useState} from 'react';
import {Bell,CalendarDays,Check,ChevronRight,Flame,Home,Pause,Play,RotateCcw,Settings,ShieldCheck,Sparkles,X} from 'lucide-react';
import {sessionFor,totalSeconds,weeks,type Exercise} from './program';
import {configureReminder} from './notifications';
import {dayNumber,loadState,saveState,streak,todayKey,type AppState} from './storage';
type Tab='home'|'plan'|'settings'; type Session={items:Exercise[];index:number;remaining:number;running:boolean};
const fmt=(n:number)=>`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;
function Figure({kind}:{kind:Exercise['visual']}){return <div className={`figure ${kind}`} aria-hidden="true"><div className="head"><div className="mouth"><i className="tongue"/><i className="arrow"/></div></div><span className="figure-label">{kind==='tongue-up'?'Zunge flächig nach oben':kind==='tongue-slide'?'Am Gaumen nach hinten':kind==='cheek-press'?'Sanft nach außen drücken':kind==='vowel'?'A · E · I · O · U':kind==='swallow'?'Zungenspitze bleibt oben':'Kiefer gerade führen'}</span></div>}
export default function App(){
 const [state,setState]=useState<AppState>(loadState); const [tab,setTab]=useState<Tab>('home'); const [session,setSession]=useState<Session|null>(null); const [showInfo,setShowInfo]=useState(false);
 useEffect(()=>saveState(state),[state]);
 useEffect(()=>{if(!session?.running)return; const id=setInterval(()=>setSession(s=>s?{...s,remaining:Math.max(0,s.remaining-1)}:s),1000); return()=>clearInterval(id)},[session?.running]);
 useEffect(()=>{if(session?.remaining===0&&session.running){if(session.index<session.items.length-1){const next=session.index+1;setSession({...session,index:next,remaining:session.items[next].seconds,running:false})}else{setSession(null);setState(s=>({...s,completed:[...new Set([...s.completed,todayKey()])]}))}}},[session]);
 const day=dayNumber(state),week=Math.ceil(day/7),dayIn=(day-1)%7,items=useMemo(()=>sessionFor(week,dayIn),[week,dayIn]),done=state.completed.includes(todayKey()),progress=Math.round(state.completed.length/84*100);
 const start=()=>setSession({items,index:0,remaining:items[0].seconds,running:true});
 if(session){const ex=session.items[session.index],elapsed=ex.seconds-session.remaining,pct=Math.round(elapsed/ex.seconds*100);return <main className="session-screen"><header><button className="icon-btn" onClick={()=>setSession(null)} aria-label="Training schließen"><X/></button><span>Übung {session.index+1} von {session.items.length}</span><span>{fmt(session.remaining)}</span></header><section className="session-card"><div className="timer-ring" style={{'--progress':`${pct*3.6}deg`} as React.CSSProperties}><div>{fmt(session.remaining)}<small>ruhig atmen</small></div></div><Figure kind={ex.visual}/><div><p className="eyebrow">JETZT</p><h1>{ex.title}</h1><p className="cue">{ex.cue}</p><ol>{ex.steps.map(s=><li key={s}>{s}</li>)}</ol></div></section><footer className="session-controls"><button className="icon-btn" onClick={()=>setSession({...session,remaining:ex.seconds,running:false})} aria-label="Neu starten"><RotateCcw/></button><button className="play" onClick={()=>setSession({...session,running:!session.running})}>{session.running?<Pause/>:<Play/>}</button><button className="icon-btn" onClick={()=>{const next=session.index+1;if(next>=session.items.length){setSession({...session,remaining:0,running:true})}else setSession({...session,index:next,remaining:session.items[next].seconds,running:true})}} aria-label="Weiter"><ChevronRight/></button></footer></main>}
 return <div className="app-shell"><main className="content">
 {tab==='home'&&<><header className="top"><div className="brand"><div className="logo">~</div><b>Leise</b></div><button className="avatar" aria-label="Profil">{week}</button></header><section className="greeting"><p className="eyebrow">WOCHE {week} · TAG {dayIn+1}</p><h1>Guten Abend.</h1><p>Heute stärken wir deine Zunge und trainieren ruhige, kontrollierte Bewegungen.</p></section><section className="today-card"><div className="today-top"><span className={done?'status done':'status'}>{done?<><Check/> erledigt</>:<><Sparkles/> heute</>}</span><span>≈ {Math.round(totalSeconds(items)/60)} Min.</span></div><div className="orb"><div className="orb-inner"><span>{items.length}</span><small>Übungen</small></div></div><h2>{done?'Training geschafft':'Deine tägliche Session'}</h2><p>{done?'Gut gemacht. Erholung gehört zum Training.':'Geführte Übungen mit Timer und klaren Hinweisen.'}</p><button className="primary" onClick={start}>{done?'Noch einmal trainieren':'Training starten'} <ChevronRight/></button></section><section className="stats"><article><Flame/><span><b>{streak(state.completed)}</b> Tage<small>Aktuelle Serie</small></span></article><article><CalendarDays/><span><b>{progress}%</b><small>Gesamtfortschritt</small></span></article></section><button className="notice" onClick={()=>setShowInfo(true)}><ShieldCheck/><span><b>Gut zu wissen</b><small>Sicher trainieren & medizinischer Hinweis</small></span><ChevronRight/></button></>}
 {tab==='plan'&&<><header className="page-head"><div><p className="eyebrow">DEIN WEG</p><h1>12 Wochen</h1></div><span>{state.completed.length}/84 Tage</span></header><div className="week-grid">{weeks.map(w=><article className={w.week===week?'week active':w.week<week?'week passed':'week'} key={w.week}><div><span>W{w.week}</span>{w.week<week&&<Check/>}</div><h3>{w.name}</h3><div className="dots">{Array.from({length:7},(_,i)=>{const n=(w.week-1)*7+i;return <i key={i} className={n<day-1?'filled':n===day-1?'current':''}/>})}</div></article>)}</div></>}
 {tab==='settings'&&<><header className="page-head"><div><p className="eyebrow">ANPASSEN</p><h1>Einstellungen</h1></div></header><section className="settings-card"><label className="setting-row"><span><Bell/><b>Tägliche Erinnerung</b><small>Auf Android zuverlässig lokal geplant</small></span><input type="checkbox" checked={state.reminderEnabled} onChange={async e=>{const ok=await configureReminder(e.target.checked,state.reminderTime);setState({...state,reminderEnabled:ok&&e.target.checked})}}/></label><label className="setting-row"><span><CalendarDays/><b>Uhrzeit</b><small>Wann passt dein Training?</small></span><input type="time" value={state.reminderTime} onChange={async e=>{const time=e.target.value;setState({...state,reminderTime:time});if(state.reminderEnabled)await configureReminder(true,time)}}/></label></section><section className="settings-card"><button className="text-row" onClick={()=>setShowInfo(true)}><ShieldCheck/><span><b>Gesundheit & Sicherheit</b><small>Hinweise zum Training</small></span><ChevronRight/></button><button className="text-row danger" onClick={()=>confirm('Fortschritt wirklich zurücksetzen?')&&setState({...state,startedAt:todayKey(),completed:[]})}><RotateCcw/><span><b>Fortschritt zurücksetzen</b><small>Lokale Trainingsdaten löschen</small></span></button></section><p className="privacy">Kein Konto. Keine Cloud. Deine Trainingsdaten bleiben auf diesem Gerät.</p></>}
 </main><nav><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/>Heute</button><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}><CalendarDays/>Programm</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings/>Einstellungen</button></nav>{showInfo&&<div className="modal-backdrop" onClick={()=>setShowInfo(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowInfo(false)}><X/></button><ShieldCheck className="modal-icon"/><h2>Trainiere achtsam</h2><p>Leise begleitet ein allgemeines Training der Mund- und Rachenmuskulatur. Die App ist kein Medizinprodukt, stellt keine Diagnose und ersetzt keine ärztliche Beratung oder Behandlung. Ein Nutzen kann nicht garantiert werden.</p><h3>Bitte medizinisch abklären</h3><p>Beobachtete Atempausen, ausgeprägte Tagesmüdigkeit, morgendliche Kopfschmerzen, nächtliches Luftschnappen oder Herz-Kreislauf-Erkrankungen können auf eine Schlafapnoe hinweisen. Wende dich damit zeitnah an eine Ärztin oder einen Arzt.</p><p>Beende eine Übung bei Schmerzen, Schwindel, Atemnot oder Kieferbeschwerden.</p><button className="primary" onClick={()=>setShowInfo(false)}>Verstanden</button></section></div>}</div>
}
